[package]
name = "bevy_pixels"
description = "Bevy plugin that uses Pixels (a tiny pixel buffer) for rendering"
version = "0.4.0"
authors = ["David Cristofaro <david@dtcristo.com>"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/dtcristo/bevy_pixels"
keywords = ["bevy", "pixels", "graphics", "2d", "framebuffer"]
categories = ["game-engines", "graphics", "rendering"]
exclude = ["images/**/*"]

[features]
default = ["x11"]

# Display server protocol support (X11 is enabled by default)
wayland = ["bevy/wayland"]
x11 = ["bevy/x11"]

[dependencies]
bevy = { version = "0.7", default_features = false, features = ["bevy_winit"] }
pixels = "0.9"

[dev-dependencies]
rand = "0.8"
