[package]
name = "bevy_pixels"
description = "Bevy plugin that uses Pixels (a tiny frame buffer) for rendering"
version = "0.1.0"
authors = ["David Cristofaro <david@dtcristo.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/dtcristo/bevy_pixels"
keywords = ["gamedev", "graphics", "bevy", "pixels", "2d", "framebuffer"]
categories = ["game-engines", "graphics", "rendering"]

[dependencies.bevy]
git = "https://github.com/dtcristo/bevy"
branch = "window-request-redraw"
default-features = false
features = ["bevy_winit"]

[dependencies.pixels]
git = "https://github.com/parasyte/pixels"
