[package]
name = "bevy_pixels"
description = "Bevy plugin that uses Pixels (a tiny pixel buffer) for rendering"
version = "0.1.0"
authors = ["David Cristofaro <david@dtcristo.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/dtcristo/bevy_pixels"
keywords = ["gamedev", "graphics", "bevy", "pixels", "2d", "framebuffer"]
categories = ["game-engines", "graphics", "rendering"]
exclude = ["images/**/*"]

[dependencies.bevy]
version = "0.5"
default-features = false
features = ["bevy_winit"]

[dependencies.pixels]
git = "https://github.com/parasyte/pixels"
rev = "9bfed17a7f51733f9042b3b524405229c628003b"

[dev-dependencies]
rand = "0.8.0"
